### ISSUE TITLE
Nice!!

### ISSUE THREAD

**Issue by ethancaballero** [Avmb/code-docstring-corpus#1]

**Comment by ethancaballero** [comment]
Do you want to add it to the request for research?

**Comment by Avmb** [comment]
Thanks, but I'm still working on the repository and I'm writing a paper about it that I expect to submit next week. I'll prefer it to be added after I've submitted the paper.

**Comment by suryabhupa** [comment]
Just to add on, I think this is absolutely fantastic. :)

**Comment by Avmb** [comment]
Thank you!

**Comment by Avmb** [comment]
Hi @ethancaballero , I've updated the corpus so that now each sample has metadata pointing to the original repository and file, I've included sample outputs of the NMT models and I've uploaded the paper on arXiv.
Can you please link this repository to OpenAI's request for research?

**Comment by ethancaballero** [comment]
https://github.com/openai/requests-for-research/pull/31

Ilya usually takes a few weeks to get around to replying.
Feel free to make any edits to the request.

**Comment by suryabhupa** [comment]
Nicely done again!

**Comment by Avmb** [comment]
Thanks!
