### ISSUE TITLE
Performance of SOTA model on this dataset

### ISSUE THREAD

**Issue by AranKomat** [Avmb/code-docstring-corpus#11]
Thank you for your interesting paper "A parallel corpus of Python functions and documentation strings for automated code documentation and code generation." You said you didn't try AST-based generation in the paper because that was not the purpose of the paper, but have you tried any stronger model on the dataset since then to see what the current SOTA would lead to? Have you been trying to create larger dataset?

**Comment by Avmb** [comment]
There is a much larger dataset in the V2 directory, though I haven't results on it yet.
