### ISSUE TITLE
Are all the descriptions used in the baseline methods?

### ISSUE THREAD

**Issue by ShilinHe** [Avmb/code-docstring-corpus#14]
Hi, it is really a great corpus! 
I noticed that some descriptions may contain parameter definitions/explanations, which may be hard to generate, so I am just wondering what your target sequence is in the baseline methods. The first sentence of the descriptions (may describe the functionality) or the entire description paragraph? Thanks!

**Comment by Avmb** [comment]
> Hi, it is really a great corpus!
Hi, thanks!

> I noticed that some descriptions may contain parameter definitions/explanations, which may be hard to generate, so I am just wondering what your target sequence is in the baseline methods. The first sentence of the descriptions (may describe the functionality) or the entire description paragraph?

All the description is used. I just did some preprocessing to remove empty lines and lines containing just non-alphanumeric characters, which tend to be used as visual separators.

**Comment by ShilinHe** [comment]
Thanks!
