### ISSUE TITLE
Can I get the source code as body directly without syntax parsing?

### ISSUE THREAD

**Issue by wanyao1992** [Avmb/code-docstring-corpus#5]
Thank you for sharing you code. In your code, the body part is represented by the syntax parse of source code which contains many symbols such as 'DCNL'  and 'DCSP'. Is it possible that I get the source code directly without syntax parsing from your code? Thanks.

**Comment by Avmb** [comment]
Just replace ' DCNL DCSP '  with '\n ', ' DCNL ' with '\n' and ' DCSP ' with ' '.
