### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by bhagat02** [Avmb/code-docstring-corpus#6]
hi ,

I want to know that in this we will train two nmt models? 
1) code2doc
2)doc2code

**Comment by Avmb** [comment]
Hi, I'm not sure I understand your question, can you expand it please?

**Comment by bhagat02** [comment]
hi,
1) Actually my question is that in this dataset we are given 2 datasets for
code generation and document generation.So, my question is that do we have
to train two NMT models
one for code generation and other for code documentation?

2)And the third data set is code only dataset in that dataset how we will
train the NMT model?

**Comment by Avmb** [comment]
Hi,

1) Yes, if you want to do both tasks you have to train two separate models.

2) That dataset is not intended to be used alone, but in combination with the others in a "semi-supervised" way. The simplest way to do it is to use it with the "Backtranslation" technique described by Sennrich et al. 2016 https://arxiv.org/abs/1511.06709

I hope this answers your questions.

Regards,
Antonio

**Comment by bhagat02** [comment]
Thank you so much for your reply.

**Comment by bhagat02** [comment]
hi,

I really want to know one more thing that if the main data set is divided
into two versions i.e one for code documentation and another for code
generation then why we need the mail parallel corpus which as all
(declaration,body and doc strings?

when actually in the NMT we will be using the Main parallel corpus?


Thank you so much in advance.

regards
Gaurav Bhagat

**Comment by Avmb** [comment]
Hi,

the main corpus is made of three aligned parts: declarations, bodies and docstrings.

For the code documentation task I concatenated each declaration with its body, to be used as source examples, and use the corresponding docstrings as target examples. For the code generation task, instead, I concatenate each declaration with its docstring as source examples and use the corresponding bodies as target examples.

But of course you are free to use any of these parts in different ways to explore different variations of the tasks. You can also use the metadata which indicates the repository, file name and line number where each example comes from, and the class and module information. This could be useful, for instance, to take into account the cross-dependencies between different code examples. How to do this is an open research question.

Best,
Antonio

**Comment by bhagat02** [comment]
Hi,


Thank you so much once again :)


Best,
Jigyasa

**Comment by Avmb** [comment]
You're welcome.
