### ISSUE TITLE
Recover original code snippets from `data_ps.all.*`

### ISSUE THREAD

**Issue by pcyin** [Avmb/code-docstring-corpus#8]
I found source code and descriptions are encoded in `data_ps.all.*`. For example, `d` is replaced with `qz`. May I know if there is a script that I can use to convert those encoded code/descriptions into their original formats? Thanks a bunch!

**Comment by Avmb** [comment]
You can recover the original with cat filename | sed 's/qz/d/g' | sed 's/qq/q/g'

but I suggest that you use the files that have already been split in train/valid/test sets.

In particular, you might want to use the version 2 of the corpus, which is bigger and has more metadata. It is in the V2 directory.

For both version 1 and version 2 there are two splits, a main split which mixes the same repositories between train, valid and test sets, and a "repository consistent" split which makes sure that each repository only ends up into one set.

**Comment by pcyin** [comment]
Got it! Thanks so much!
